version: '2'
services: 
  mongo:
    image: mongo
    ports: 
      - 27017:27017
  compras:
    build: ./compras
    ports: 
      - 3000:3000
    depends_on: 
      - mongo
      - avisos
    environment: 
      - MONGO_URL=mongodb://mongo/todocartoes
  avisos:
    build: ./avisos
    ports: 
      - 3001:3001